package com.weaone.themoa.domain.policy.rag.dto;

public enum CandidateSource {
    VECTOR_ORIGINAL_QUERY,
    VECTOR_NORMALIZED_QUERY,
    VECTOR_INTENT_QUERY,
    VECTOR_INTENT_INITIAL,
    VECTOR_INTENT_RETRY,
    VECTOR_INTENT_NO_THRESHOLD,
    VECTOR_EXPANDED_QUERY,
    VECTOR_CATEGORY_QUERY,
    EXACT_TITLE,
    TITLE_PHRASE,
    LEXICAL_INDEX,
    CATEGORY_SIGNAL,
    BROAD_ELIGIBLE_POOL,
    BROAD_FALLBACK,
    MYSQL_TITLE,
    MYSQL_KEYWORD,
    MYSQL_SUMMARY,
    MYSQL_CATEGORY,
    MYSQL_FALLBACK
}
